<?php if (count($flash) > 0) : ?>
    <ul>
        <?php foreach ($flash as $messages) : ?>
            <?php foreach ($messages as $message) : ?>
                <li><?= $message ?></li>
            <?php endforeach ?>
        <?php endforeach ?>
    </ul>
<?php endif ?>

<a href="/posts/new">Новый пост</a>

<form action="/posts" method="POST">
    <label>
        <a href="?page=<?= $page < 2 ? 1 : $page - 1 ?>">Previous page</a>
        <a href="?page=<?= $page < $numberOfPages ? $page + 1 : $numberOfPages  ?>">Next page</a>
                <table>
                    <?php foreach ($posts as $post): ?>
                        <tr>
                            <td>
                                <a href="/posts/<?= $post['id'] ?>"><?= htmlspecialchars($post['name']) ?></a>
                                <input type="hidden" name="_METHOD" value="DELETE">
                                <input type="submit" value="Remove">
                            </td>
                        </tr>
                    <?php endforeach ?>
                </table>
    </label>
        </form>


