<?php if (count($flash) > 0): ?>
    <ul>
        <?php foreach ($flash as $messages): ?>
            <?php foreach ($messages as $message): ?>
                <li><?= $message ?></li>
            <?php endforeach ?>
        <?php endforeach ?>
    </ul>
<?php endif ?>

<?php if($user): ?>
    <div><?= $user['name'] ?></div>
    <form action="/login", method="post">
        <input type="hidden" name="_METHOD" value="DELETE">
        <input type="submit" value="Sign Out">
    </form>
<?php else: ?>
    <form action="/login", method="post">
        <label>
            Name
            <input type='text' name="user[name]">
        </label>
        <label>
            Password
            <input type='text' name="user[password]">
        </label>
        <input type="submit" value="Sign In">
    </form>
<?php endif; ?>
